**broadcasting과 연산**

In [19]:
import pandas as pd
a1 = [[1,2,3], [4,5,6,], [7,8,9]]
df1 = pd.DataFrame(a1, columns=list("ABC"), index=list("가나다"))
df2 = df1.reindex(columns=list("BCA"), index=list("나다가")).copy()
sr1 = df1.loc["나"]
df3 = df1.iloc[:2,:2]

In [3]:
df1 * df1

    A   B   C
가   1   4   9
나  16  25  36
다  49  64  81

In [5]:
df1

   A  B  C
가  1  2  3
나  4  5  6
다  7  8  9

In [6]:
df2

   B  C  A
나  5  6  4
다  8  9  7
가  2  3  1

In [7]:
df1 + df2 # 라벨에 맞춰서 연산을 한다.

    A   B   C
가   2   4   6
나   8  10  12
다  14  16  18

In [9]:
df3

   A  B
가  1  2
나  4  5

In [11]:
df1 + df3 # 연산 함수가 아니라 연산자로 쉽게 연산이 된다.

     A     B   C
가  2.0   4.0 NaN
나  8.0  10.0 NaN
다  NaN   NaN NaN

In [16]:
df1.add(df3,fill_value = 0)

     A     B    C
가  2.0   4.0  3.0
나  8.0  10.0  6.0
다  7.0   8.0  9.0

In [20]:
sr1

A    4
B    5
C    6
Name: 나, dtype: int64

In [22]:
df1

   A  B  C
가  1  2  3
나  4  5  6
다  7  8  9

In [21]:
df1 + sr1 #기본 디폴트값은 위에서 아래로 브로드캐스팅하는 것이다.

    A   B   C
가   5   7   9
나   8  10  12
다  11  13  15

In [23]:
  df1.add(sr1, axis = 0) #라벨이 안맞아서 nan

    A   B   C
A NaN NaN NaN
B NaN NaN NaN
C NaN NaN NaN
가 NaN NaN NaN
나 NaN NaN NaN
다 NaN NaN NaN